precice.pyx

With reference to https://github.com/precice/precice/issues/366, the configuration call is transferred into the interface initialization call 
Closes https://github.com/precice/python-bindings/issues/11

Moving configure call into interface initialization

---

docs/MigrationGuide.md

This PR adds a migration guide in the `docs/` folder to help users who were using the old python bindings and are now moving to the new python bindings. Closes https://github.com/precice/python-bindings/issues/27

Adding Migration Guide 

---

README.md
setup.py

We use the current preCICE version and append an independent version number for the python bindings.
Closes #31

Implement versioning strategy

---

README.md
setup.py

If you want to try out the release see https://pypi.org/project/pyprecice/2.0.0.2rc2/.
This release provides documentation fixes and improves the integration into PyPI.
A draft of the release is provided at https://github.com/precice/python-bindings/releases/tag/untagged-c5d23f8074e6a20b86e1.

Release v2.0.0.2

---

setup.py

Clean-up of setup.py

---

CHANGELOG.md
precice.pyx
setup.py
test/test_bindings_module.pyx

In a parallel coupling case, ranks which have no part of the coupling interface will call the write data functionality with empty data structures. The bindings need to handle this as the main preCICE API allows this.

Handle writing of empty arrays to preCICE

---

cyprecice/cyprecice.pxd
cyprecice/cyprecice.pyx

Closes #72.
`from mpi4py import MPI` has to be imported in the `pyx`, not in the `pxd` file.

Fix bug: It looks like opal_init failed for some reason

---

CHANGELOG.md
cyprecice/cyprecice.pyx
test/test_bindings_module.py

Check that input is array_like, if required

---

.github/workflows/run-solverdummy.yml

This test is mainly helping to detect errors when running the python bindings.
This is especially useful for MPI-related issues, such as the one described here: https://github.com/precice/python-bindings/issues/8#issuecomment-575329609

Test solverdummy

---

solverdummy/README.md

Closes #110
Removes the documentation for the parallel version of the solver dummy. This is consistent with other solverdummies (https://github.com/precice/precice/blob/develop/examples/solverdummies/README.md and https://github.com/precice/fortran-module/blob/develop/examples/solverdummy/README.md). The solverdummies should be as simple as possible and therefore supporting parallel runs is out-of-scope.

Remove documentation for parallel version

---

.github/workflows/build-and-test.yml
.github/workflows/build-spack.yml
.github/workflows/check-pep8.yml
.github/workflows/run-solverdummy.yml

Resulting from https://github.com/precice/python-bindings/pull/117, since tests are currently not triggered by PRs from forks.

Run CI also on PRs

---

cyprecice/SolverInterface.pxd
cyprecice/cyprecice.pyx
test/SolverInterface.cpp
test/test_bindings_module.py

Adding two new API functions related to functionality for direct access to received meshes. More details: https://github.com/precice/precice/pull/1033
closes #123

Adding direct mesh access experimental functions

---

README.md

This mention a C++ compiler as dependency for building the bindings in the README. It was pointed out that installation of the bindings fails, if there is no C++ compiler installed.
Do we actually need MPI as a dependency as well?

Add C++ compiler as dependency

---

examples/solverdummy/README.md
examples/solverdummy/solverdummy.py

The mesh name was removed from the input arguments to the other solverdummies in https://github.com/precice/precice/pull/1256. The change is now incorporated in the solverdummy in this repository for consistency.

Remove mesh_name from solverdummy input arguments

---

spack/README.md

This fixes the formatting of the lists in markdown such that they are rendered correctly on GitHub and by other Markdown rendering tools, e.g. Visual Studio Code.
While doing so I also fixed some erroneous commands and rephrased some parts to be more precise.

Fix formatting of Spack documentation and make documentation clearer

---

.github/workflows/build-and-test.yml
.github/workflows/run-solverdummy.yml
cyprecice/cyprecice.pyx
pyproject.toml
setup.py

This PR resolves a warning and an error in the action set of `build-and-test`. The warning was:
```bash
warning: cyprecice/cyprecice.pyx:1211:57: local variable '_value' referenced before assignment
```
and the error was
```bash
/home/runner/work/python-bindings/python-bindings/precice/SolverInterface.hpp:7:10: fatal error: precice/Version.h: No such file or directory
7 | #include "precice/Version.h"
|          ^~~~~~~~~~~~~~~~~~~
```

Repairing warnings and error regarding Version.h by using pkgconfig to link to preCICE

---

.github/workflows/build-and-test.yml
.github/workflows/build-env.yml
.github/workflows/build-spack.yml
.github/workflows/pythonpublish.yml
.github/workflows/run-solverdummy.yml
CHANGELOG.md
cyprecice/cyprecice.pyx
pyproject.toml
setup.py
spack/README.md
spack/ci-spack-pyprecice-deps-2204.dockerfile
spack/repo/packages/py-pyprecice/package.py
tools/releasing/packaging/docker/Dockerfile

Release for preCICE [v2.5.0](https://github.com/precice/precice/releases/tag/v2.5.0)
Main features:
* Bindings now use pkgconfig to determine flags and link to preCICE https://github.com/precice/python-bindings/pull/149

Release v2.5.0.0

---

cyprecice/SolverInterface.pxd
cyprecice/cyprecice.pyx
test/SolverInterface.cpp
test/test_bindings_module.py

This PR adds nearest neighbour gradient related API to python bindings

Add gradient related API

---

cyprecice/cyprecice.pyx
precice/__init__.py

- Added docstrings for some functions
- Removed `return` statement in l. 593 of `cyprecice/cyprecice.pxy` (please confirm that this is correct)
- Removed `import` statements in `__init__.py` since these functions do no longer exist.

Adapted compatibility-precice-dev branch

---

.github/workflows/build-and-test.yml
cyprecice/SolverInterface.pxd
cyprecice/cyprecice.pyx
examples/solverdummy/solverdummy.py
test/SolverInterface.cpp
test/test_bindings_module.py

API changes are in line with https://github.com/precice/precice/pull/1588

Use mesh name and data name instead of IDs

---

CHANGELOG.md

Development release for easier development and switching between preCICE v3.0.0.0dev0 and older versions.

Release v3.0.0.0dev0

---

CHANGELOG.md
precice/_version.py
setup.cfg

This release is necessary to resolve https://github.com/precice/python-bindings/issues/185. Versioneer was not able to get the correct version, which led to failure of deployment on PyPI.

Bugfix release v2.5.0.4

---

.github/workflows/build-docker.yml

This disables building the Docker image on push to master, which was first enabled in #186. This workflow was simply not triggered before, but currently fails #191.
Publishing such a Docker image is not needed for the system tests anymore.
@BenjaminRodenberg @IshaanDesai I am directly contributing to the master branch as a hotfix, since this only fixes (disables) the broken GitHub Actions workflow.

Disable build-docker workflow on push to master

---

setup.py

This PR fixes the numpy include order.
This leads to the system numpy being considered after local installations (venv or pip --user).
This is the reason why cython failed to compile when using numpy>=2 with a system numpy<2.

Fix numpy include order

---

CHANGELOG.md
setup.py

This is a bugfix release of the bindings. The order in which NumPy is included in the build setup is changed to prevent a conflict between the system installed NumPy, and the NumPy installed via pip.

Release v3.1.1

---

CHANGELOG.md
pyproject.toml
setup.py
spack/repo/packages/py-pyprecice/package.py

Requiring setuptools>=61 allows us to remove a noisy warning that always shows up when building with spack. It also allows us to simplify the `setup.py`. Setuptools>=61 guarantees that pyproject.toml is used.

Require setuptools>=61

---

CHANGELOG.md
pyproject.toml
setup.py
spack/repo/packages/py-pyprecice/package.py

I would suggest to restrict the numpy version to `numpy<2` since the newest numpy is not well supported by our CI pipeline (see #212).

Restrict to numpy < 2 and setuptools < 72 for better compatibiltiy with CI pipeline

---

pyproject.toml
setup.py
spack/repo/packages/py-pyprecice/package.py

Closes https://github.com/precice/python-bindings/issues/219
To some degree I would also consider this as a bugfix since Numpy support was implemented for `3.1.1` in #204 and broken in `3.1.2` via #213.

Allow numpy 2 for pyprecice>=3.1.1

---

setup.py

This PR adds a more helpful error message when the python bindings cannot find preCICE using pkg-config.
It also silences the NumPy warning to prevent it from distracting from the actual problem.

Improve install error messages

---

changelog-entries/224.md
cyprecice/Participant.pxd
cyprecice/cyprecice.pyx
test/Participant.cpp
test/test_bindings_module.py

This PR adds the API for runtime remeshing to the python bindings.
The feature is available in the develop version of preCICE https://github.com/precice/precice/pull/2070
As the limitations are still changing, I refer the user to the online documentation.

Add API for runtime remeshing

---

.github/workflows/build-and-test.yml
.github/workflows/build-docker.yml
.github/workflows/build-env.yml
.github/workflows/build-spack.yml
.github/workflows/check-markdown.yml
.github/workflows/pythonpublish.yml
.github/workflows/run-solverdummy.yml
.markdownlint.json
CHANGELOG.md
README.md
docs/MigrationGuide.md
docs/ReleaseGuide.md
examples/solverdummy/README.md
pyproject.toml
setup.py
spack/README.md
spack/ci-spack-pyprecice-deps-2404.dockerfile
spack/repo/packages/py-pyprecice/package.py
tools/releasing/packaging/docker/Dockerfile

Backports some trivial changes to v2.5.0.
Compatibility release for preCICE [v2.5.1](https://github.com/precice/precice/releases/tag/v2.5.1).
Closes #203

Release v2.5.1.0

---

.github/workflows/build-and-test.yml
.github/workflows/run-solverdummy.yml

Required by recent pip versions (introduced with upgrade of Ubuntu base image for CI)

Use `venv` for CI

---

changelog-entries/226.md
cyprecice/Participant.pxd
cyprecice/cyprecice.pyx
test/Participant.cpp

The profiling API from https://github.com/precice/precice/pull/1657 is added to the bindings. This PR should not be merged before https://github.com/precice/precice/pull/1657
The need for the profiling API arose from the need to accurately profile load balancing in https://github.com/precice/micro-manager/pull/141

Add experimental profiling API

---

cyprecice/Participant.pxd

This PR adds exception support for the entire API.
Note that both `const` and `except` are incompatible, hence I had to remove the `const` member specifiers from the API.
This shouldn't be a problem as `const` is purely decorative as there is no `const` usage in python.
This implementation translates all exceptions into `RuntimeError`s on the python side. We could provide a custom `Error` as part of the `precice` module to make this cleaner.
Closes #173

Add exception support

---

cyprecice/Participant.pxd
cyprecice/cyprecice.pyx
test/Participant.cpp
test/test_bindings_module.py

Adds the `writeAndMapData` and `mapAndReadData`, together with an (amazing) test.
@IshaanDesai could you please review? We pair-programmed this with @BenjaminRodenberg, thus a third pair of eyes would be useful here.

Add API functions for Just-in-time mapping

---

changelog-entries/233.md
examples/solverdummy/requirements.txt

Title is self-explanatory. Closes #232

Update requirements of the solver dummy

---

CHANGELOG.md
changelog-entries/193.md
changelog-entries/221.md
changelog-entries/224.md
changelog-entries/226.md
changelog-entries/231.md
changelog-entries/233.md

This repository does not have too many contributions or parallel developments, so adding individual changelog entries is an overkill. This PR reverts to using one file for the changelog entries.

Move from adding individual changelog entries to directly editing the main file

---

CHANGELOG.md
cyprecice/cyprecice.pyx

See #236 
Note: this change is untested, as I do not have time to set up the project locally right now.

Flatten coordinate array in `map_and_read_data`

---

CHANGELOG.md
cyprecice/cyprecice.pyx

From the discussion in https://github.com/precice/python-bindings/issues/236, it emerged that there is confusion about the acceptable ways to provide multidimensional data structures to the API. The examples in the docstrings primarily show that NumPy arrays can be used, but the API also accepts a list of lists, or a list of tuples. This PR modifies the docstrings to clearly state this flexibility of the API.

Modify docstrings to clearly state the flexibility of the API in accepting multidimensional data structures
